package entity.meeting;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

public class Meeting {
    private String id;
    private String description;
    private final String group;
    private LocalDateTime date;

    /**
     * Creates a new meeting instance without a due date.
     *
     * @param meetingID      The unique ID for this meeting (autogenerated by MongoDB)
     * @param description the description for this meeting
     * @param groupID     the group this meeting is associated with
     */
    public Meeting(String meetingID,
                String description,
                String groupID) {
        this.id = meetingID;
        this.description = description;
        this.group = groupID;
    }

    public String getID() {
        return this.id;
    }

    public void setID(String meetingID) {
        this.id = meetingID;
    }

    public String getDescription() {
        return description;
    }

    public String getGroup() {
        return group;
    }

    public Optional<LocalDateTime> getDate() {
        return Optional.ofNullable(date);
    }

    /**
     * Updates the description of this meeting.
     *
     * @param description The new description text
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Sets the due date of the meeting.
     *
     * @param date The deadline for the meeting
     */
    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    /**
     * Check whether this meeting has a due date.
     *
     * @return Whether this meeting has a set due date.
     */
    public Boolean hasDate() {
        return date != null;
    }

}
