package entity.task;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

public class Task {
    private String id;
    private String description;
    private boolean completed;
    private final String group;
    private final List<String> assignees;
    private LocalDateTime dueDate;

    /**
     * Creates a new Task instance with the given due date.
     *
     * @param taskID      The unique ID for this task (autogenerated by MongoDB)
     * @param description The text description of the task
     * @param groupID     The group to which this task belongs
     * @param completed   Whether the task was completed or not
     * @param assignees   The assigned users to this task
     * @param dueDate     the due date for this task
     */
    public Task(String taskID,
                String description,
                String groupID,
                boolean completed,
                List<String> assignees,
                LocalDateTime dueDate) {
        this.id = taskID;
        this.description = description;
        this.dueDate = dueDate;
        this.group = groupID;
        this.completed = completed;
        this.assignees = assignees;
    }

    /**
     * Creates a new Task instance without a due date.
     *
     * @param taskID      The unique ID for this task (autogenerated by MongoDB)
     * @param description the description for this task
     * @param groupID     the group this task is associated with
     * @param completed   Whether the task was completed or not
     * @param assignees   The assigned users to this task
     */
    public Task(String taskID,
                String description,
                String groupID,
                boolean completed,
                List<String> assignees) {
        this.id = taskID;
        this.description = description;
        this.group = groupID;
        this.completed = completed;
        this.assignees = assignees;
    }

    public String getID() {
        return this.id;
    }

    public void setID(String taskID) {
        this.id = taskID;
    }

    public String getDescription() {
        return description;
    }

    public String getGroup() {
        return group;
    }

    public List<String> getAssignees() {
        return assignees;
    }

    public Optional<LocalDateTime> getDueDate() {
        return Optional.ofNullable(dueDate);
    }

    /**
     * Check whether this task is completed.
     * 
     * @return {@code true} if the task is marked as completed, otherwise
     *         {@code false}.
     */
    public boolean isCompleted() {
        return completed;
    }

    /**
     * Updates the description of this task.
     *
     * @param description The new description text
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Marks this task as completed.
     */
    public void markCompleted() {
        this.completed = true;
    }

    /**
     * Marks this task as incomplete.
     */
    public void markIncomplete() {
        this.completed = false;
    }

    /**
     * Sets the due date of the task.
     *
     * @param dueDate The deadline for the task
     */
    public void setDueDate(LocalDateTime dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * Check whether this task has a due date.
     * 
     * @return Whether this task has a set due date.
     */
    public Boolean hasDueDate() {
        return dueDate != null;
    }

    /**
     * Determines whether this task is overdue.
     * 
     * @return {@code true} if the task is incomplete,
     *         and the due date has passed; otherwise {@code false}.
     */
    public boolean isOverdue() {
        if (this.hasDueDate()) {
            return !completed
                    && dueDate.isBefore(LocalDateTime.now());
        }
        return false;
    }

    /**
     * Adds a user to the list of assignees.
     * 
     * @param userID UserID of the User to assign to this task to
     */

    public void addAssignee(String userID) {
        assignees.add(userID);
    }

    /**
     * Removes a user from the list of assignees.
     * 
     * @param userID The user to remove from assignment
     */
    public void removeAssignee(String userID) {
        assignees.remove(userID);
    }

    /**
     * Updates a new list of assignees for this task.
     *
     * @param assignees the new list of assigned users.
     */
    public void setAssignees(List<String> assignees) {
        if (assignees == null) return;
        this.assignees.clear();
        this.assignees.addAll(assignees);
    }
}
