package entity.task;

import java.time.LocalDateTime;
import java.util.List;

public class TaskFactory {
    /**
     * Create a new task instance with a deadline.
     *
     * @param taskID      The unique ID for this task (autogenerated by MongoDB)
     * @param description The text description of the task
     * @param groupID     The group to which this task belongs
     * @param completed   Whether the task was completed or not
     * @param assignees   The assigned users to this task
     * @param dueDate     the due date for this task
     *
     * @return            A task object with a due date
     */
    public Task createWithDeadline(String taskID,
                                   String description,
                                   String groupID,
                                   boolean completed,
                                   List<String> assignees,
                                   LocalDateTime dueDate) {
        return new Task(taskID, description, groupID, completed, assignees, dueDate);
    }

    /**
     * Create a new task instance without a deadline.
     *
     * @param taskID      The unique ID for this task (autogenerated by MongoDB)
     * @param description the description for this task
     * @param groupID     the group this task is associated with
     * @param completed   Whether the task was completed or not
     * @param assignees   The assigned users to this task
     *
     * @return            A task object without a due date
     */
    public Task createWithoutDeadline(String taskID,
                                      String description,
                                      String groupID,
                                      boolean completed,
                                      List<String> assignees) {
        return new Task(taskID, description, groupID, completed, assignees);
    }
}
